package oop.solutions;

import java.util.Objects;

/**
 * ExerciseSet6Solution.java
 *
 * Solutions for Exercise Set 6: Records and Modern OOP.
 * Covers: Java records (auto-generated equals/hashCode/toString, immutability),
 *         compact constructors for validation, custom instance methods on records,
 *         and both classic and pattern-matching instanceof.
 */
public class ExerciseSet6Solution {

    public static void main(String[] args) {

        // === Exercise 6.1: Point Record ===
        System.out.println("=== Exercise 6.1: Point Record ===");

        PointRecord p1 = new PointRecord(3.0, 4.0);
        PointRecord p2 = new PointRecord(3.0, 4.0);
        PointRecord p3 = new PointRecord(0.0, 0.0);

        // toString() is auto-generated by the record compiler.
        System.out.println("p1: " + p1); // Output: p1: PointRecord[x=3.0, y=4.0]
        System.out.println("p2: " + p2); // Output: p2: PointRecord[x=3.0, y=4.0]

        // equals() compares by value — two distinct objects with the same fields are equal.
        System.out.println("p1.equals(p2): " + p1.equals(p2)); // Output: p1.equals(p2): true
        System.out.println("p1 == p2:      " + (p1 == p2));    // Output: p1 == p2:      false

        // hashCode() is consistent with equals().
        System.out.println("Same hash: " + (p1.hashCode() == p2.hashCode()));
        // Output: Same hash: true

        // Records have no setters — they are immutable by design.
        // p1.x = 10.0; // This would not compile.

        // Custom instance methods work normally on records.
        System.out.printf("Distance p1 to p3: %.2f%n", p1.distanceTo(p3));
        // Output: Distance p1 to p3: 5.00

        // translate() returns a new PointRecord; p1 is unchanged.
        PointRecord p4 = p1.translate(1.0, 1.0);
        System.out.println("p1 after translate call: " + p1); // Output: p1 after translate call: PointRecord[x=3.0, y=4.0]
        System.out.println("p4 (new):               " + p4);  // Output: p4 (new):               PointRecord[x=4.0, y=5.0]

        // === Exercise 6.2: Range Record ===
        System.out.println("\n=== Exercise 6.2: Range Record ===");

        Range r1 = new Range(1.0, 10.0);
        Range r2 = new Range(5.0, 15.0);

        System.out.println("r1: " + r1);           // Output: r1: Range[min=1.0, max=10.0]
        System.out.println("r1.width(): " + r1.width()); // Output: r1.width(): 9.0

        System.out.println("r1.contains(5.0): "  + r1.contains(5.0));  // Output: r1.contains(5.0): true
        System.out.println("r1.contains(10.0): " + r1.contains(10.0)); // Output: r1.contains(10.0): true
        System.out.println("r1.contains(11.0): " + r1.contains(11.0)); // Output: r1.contains(11.0): false

        // intersect() returns the overlapping sub-range.
        Range overlap = r1.intersect(r2);
        System.out.println("r1 intersect r2: " + overlap);
        // Output: r1 intersect r2: Range[min=5.0, max=10.0]

        // Compact constructor rejects an invalid range.
        try {
            Range bad = new Range(10.0, 1.0);
        } catch (IllegalArgumentException e) {
            System.out.println("Caught: " + e.getMessage());
            // Output: Caught: min (10.0) must be <= max (1.0).
        }

        // No-overlap case.
        Range r3 = new Range(20.0, 30.0);
        try {
            r1.intersect(r3);
        } catch (IllegalArgumentException e) {
            System.out.println("Caught: " + e.getMessage());
            // Output: Caught: Ranges do not overlap.
        }

        // === Exercise 6.3: Downcasting and Pattern Matching ===
        System.out.println("\n=== Exercise 6.3: Downcasting and Pattern Matching ===");

        Shape6[] shapes = {
            new Circle6(5.0),
            new Rectangle6(4.0, 6.0),
            new Triangle6(3.0, 4.0, 5.0)
        };

        System.out.println("--- Classic instanceof + explicit cast ---");
        for (Shape6 s : shapes) {
            describeClassic(s);
        }
        // Output:
        // Circle with radius 5.00 — area=78.54
        // Rectangle 4.00 x 6.00 — area=24.00
        // Triangle with sides 3.00, 4.00, 5.00 — area=6.00

        System.out.println("--- Pattern-matching instanceof (Java 16+) ---");
        for (Shape6 s : shapes) {
            describePatternMatch(s);
        }
        // Output (identical to classic version):
        // Circle with radius 5.00 — area=78.54
        // Rectangle 4.00 x 6.00 — area=24.00
        // Triangle with sides 3.00, 4.00, 5.00 — area=6.00
    }

    // -------------------------------------------------------------------------
    // Exercise 6.1 — Point Record
    // -------------------------------------------------------------------------

    /**
     * An immutable (x, y) coordinate expressed as a Java record.
     * The compiler auto-generates: a canonical constructor, getters (x(), y()),
     * equals(), hashCode(), and toString().
     */
    record PointRecord(double x, double y) {

        /** Returns the Euclidean distance to another PointRecord. */
        double distanceTo(PointRecord other) {
            double dx = this.x - other.x;
            double dy = this.y - other.y;
            return Math.sqrt(dx * dx + dy * dy);
        }

        /**
         * Returns a NEW PointRecord displaced by (dx, dy).
         * Records are immutable, so "modification" always produces a new instance.
         */
        PointRecord translate(double dx, double dy) {
            return new PointRecord(x + dx, y + dy);
        }
    }

    // -------------------------------------------------------------------------
    // Exercise 6.2 — Range Record with Compact Constructor
    // -------------------------------------------------------------------------

    /**
     * An immutable numeric range [min, max].
     * The compact constructor validates the invariant min <= max before
     * the record's fields are assigned.
     */
    record Range(double min, double max) {

        /** Compact constructor: validation runs before the fields are set. */
        Range {
            if (min > max) {
                throw new IllegalArgumentException(
                        "min (" + min + ") must be <= max (" + max + ").");
            }
        }

        /** Returns true if the given value falls within [min, max] inclusive. */
        boolean contains(double value) {
            return value >= min && value <= max;
        }

        /** Returns the width of the range (max - min). */
        double width() {
            return max - min;
        }

        /**
         * Returns a new Range representing the overlap of this range and other.
         * @throws IllegalArgumentException if the ranges do not overlap.
         */
        Range intersect(Range other) {
            double lo = Math.max(this.min, other.min);
            double hi = Math.min(this.max, other.max);
            if (lo > hi) {
                throw new IllegalArgumentException("Ranges do not overlap.");
            }
            return new Range(lo, hi); // The compact constructor validates again.
        }
    }

    // -------------------------------------------------------------------------
    // Exercise 6.3 — Downcasting and Pattern Matching
    // -------------------------------------------------------------------------

    /** Abstract base for the shape hierarchy used in exercise 6.3. */
    static abstract class Shape6 {
        abstract double area();
    }

    static class Circle6 extends Shape6 {
        final double radius;

        Circle6(double radius) { this.radius = radius; }

        @Override
        public double area() { return Math.PI * radius * radius; }
    }

    static class Rectangle6 extends Shape6 {
        final double width;
        final double height;

        Rectangle6(double width, double height) {
            this.width  = width;
            this.height = height;
        }

        @Override
        public double area() { return width * height; }
    }

    static class Triangle6 extends Shape6 {
        final double a;
        final double b;
        final double c;

        Triangle6(double a, double b, double c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }

        /** Area via Heron's formula. */
        @Override
        public double area() {
            double s = (a + b + c) / 2.0;
            return Math.sqrt(s * (s - a) * (s - b) * (s - c));
        }
    }

    /**
     * Classic style: instanceof check followed by an explicit cast.
     * The cast is necessary to access type-specific fields or methods.
     */
    static void describeClassic(Shape6 shape) {
        if (shape instanceof Circle6) {
            Circle6 c = (Circle6) shape; // Explicit downcast required.
            System.out.printf("Circle with radius %.2f — area=%.2f%n", c.radius, c.area());
        } else if (shape instanceof Rectangle6) {
            Rectangle6 r = (Rectangle6) shape;
            System.out.printf("Rectangle %.2f x %.2f — area=%.2f%n", r.width, r.height, r.area());
        } else if (shape instanceof Triangle6) {
            Triangle6 t = (Triangle6) shape;
            System.out.printf("Triangle with sides %.2f, %.2f, %.2f — area=%.2f%n",
                    t.a, t.b, t.c, t.area());
        }
    }

    /**
     * Modern style (Java 16+): the pattern variable is bound in the same
     * expression that performs the test — no separate cast statement needed.
     */
    static void describePatternMatch(Shape6 shape) {
        if (shape instanceof Circle6 c) {
            // c is already typed as Circle6 within this block.
            System.out.printf("Circle with radius %.2f — area=%.2f%n", c.radius, c.area());
        } else if (shape instanceof Rectangle6 r) {
            System.out.printf("Rectangle %.2f x %.2f — area=%.2f%n", r.width, r.height, r.area());
        } else if (shape instanceof Triangle6 t) {
            System.out.printf("Triangle with sides %.2f, %.2f, %.2f — area=%.2f%n",
                    t.a, t.b, t.c, t.area());
        }
    }
}
